l=[]
n=int(input("How Many Numbers to be added in the list"))
print("Enter Elements onr by one")
for i in range(0,n):
    l.append(input())
print("\n\n Created List")
print(l)
m=int(input("Enter the position of the element to be removed"))
l.pop(m)
print("\n\n List After removing selected elements")
print(l)
l.sort()
print("\n\n List in ascending order ")
print(l)
l.reverse()
print("\n\n List in Descending order ")
print(l)
print("After sum() method")
print(sum(l))
print("insert()method")
l.insert(5,90)
print(l)
print("after Count() method")
print(l.count(67))
