L=[]
n=int(input("How Many numbers to be added in the list :"))
print("Enter elements one by one")
for i in range(0,n):
    L.append(input())
    print("\n\n Created List")
    print(L)
    m=int(input("Enter the position number to element to remove :"))
    L.pop(m)
    print("\n \n List after removing selected elements :")
    print(L)
    L.sort()
    print("\n \n List in ascending Order")
    print(L)
    L.reverse()
    print("\n \n List in Descending order")
    print(L)
    print('After sum() method')
    print(sum(L))
    print('Insert() method')
    L.insert(5,90)
    print(L)
    print('After count() method')
    print(L.count(67))
